# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

os: Visual Studio 2015 CTP 6

build_script:
  - travis-tool.sh install_github hadley/devtools
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc GenomicRanges

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

branches:
  only:
    - master

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    _R_CHECK_FORCE_SUGGESTS_: 0
    # R_BUILD_ARGS: "--no-build-vignettes"
    # R_CHECK_ARGS: "--as-cran --ignore-vignettes"

  matrix:
  - R_VERSION: release
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

matrix:
  allow_failures:
    - R_VERSION: devel

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
