// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// bed12toexons.cpp
cpp11::writable::data_frame bed12toexons_impl(cpp11::data_frame x);
extern "C" SEXP _valr_bed12toexons_impl(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bed12toexons_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(x)));
  END_CPP11
}
// closest.cpp
cpp11::writable::data_frame closest_impl(cpp11::data_frame gdf_x, cpp11::data_frame gdf_y, cpp11::integers grp_idx_x, cpp11::integers grp_idx_y, std::string suffix_x, std::string suffix_y);
extern "C" SEXP _valr_closest_impl(SEXP gdf_x, SEXP gdf_y, SEXP grp_idx_x, SEXP grp_idx_y, SEXP suffix_x, SEXP suffix_y) {
  BEGIN_CPP11
    return cpp11::as_sexp(closest_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_x), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(grp_idx_x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(grp_idx_y), cpp11::as_cpp<cpp11::decay_t<std::string>>(suffix_x), cpp11::as_cpp<cpp11::decay_t<std::string>>(suffix_y)));
  END_CPP11
}
// complement.cpp
cpp11::writable::data_frame complement_impl(cpp11::data_frame gdf, cpp11::data_frame genome);
extern "C" SEXP _valr_complement_impl(SEXP gdf, SEXP genome) {
  BEGIN_CPP11
    return cpp11::as_sexp(complement_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(genome)));
  END_CPP11
}
// coverage.cpp
cpp11::writable::data_frame coverage_impl(cpp11::data_frame gdf_x, cpp11::data_frame gdf_y, cpp11::integers x_grp_indexes, cpp11::integers y_grp_indexes, int min_overlap);
extern "C" SEXP _valr_coverage_impl(SEXP gdf_x, SEXP gdf_y, SEXP x_grp_indexes, SEXP y_grp_indexes, SEXP min_overlap) {
  BEGIN_CPP11
    return cpp11::as_sexp(coverage_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_x), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x_grp_indexes), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(y_grp_indexes), cpp11::as_cpp<cpp11::decay_t<int>>(min_overlap)));
  END_CPP11
}
// dist.cpp
cpp11::writable::data_frame dist_impl(cpp11::data_frame gdf_x, cpp11::data_frame gdf_y, cpp11::integers x_grp_indexes, cpp11::integers y_grp_indexes, std::string distcalc);
extern "C" SEXP _valr_dist_impl(SEXP gdf_x, SEXP gdf_y, SEXP x_grp_indexes, SEXP y_grp_indexes, SEXP distcalc) {
  BEGIN_CPP11
    return cpp11::as_sexp(dist_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_x), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x_grp_indexes), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(y_grp_indexes), cpp11::as_cpp<cpp11::decay_t<std::string>>(distcalc)));
  END_CPP11
}
// flank.cpp
cpp11::writable::data_frame flank_impl(cpp11::data_frame df, cpp11::data_frame genome, double both, double left, double right, bool fraction, bool stranded, bool trim);
extern "C" SEXP _valr_flank_impl(SEXP df, SEXP genome, SEXP both, SEXP left, SEXP right, SEXP fraction, SEXP stranded, SEXP trim) {
  BEGIN_CPP11
    return cpp11::as_sexp(flank_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(df), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(genome), cpp11::as_cpp<cpp11::decay_t<double>>(both), cpp11::as_cpp<cpp11::decay_t<double>>(left), cpp11::as_cpp<cpp11::decay_t<double>>(right), cpp11::as_cpp<cpp11::decay_t<bool>>(fraction), cpp11::as_cpp<cpp11::decay_t<bool>>(stranded), cpp11::as_cpp<cpp11::decay_t<bool>>(trim)));
  END_CPP11
}
// gcoverage.cpp
cpp11::writable::data_frame gcoverage_impl(cpp11::data_frame gdf, cpp11::doubles max_coords);
extern "C" SEXP _valr_gcoverage_impl(SEXP gdf, SEXP max_coords) {
  BEGIN_CPP11
    return cpp11::as_sexp(gcoverage_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(max_coords)));
  END_CPP11
}
// intersect.cpp
cpp11::writable::data_frame intersect_impl(cpp11::data_frame gdf_x, cpp11::data_frame gdf_y, cpp11::integers x_grp_indexes, cpp11::integers y_grp_indexes, bool invert, std::string suffix_x, std::string suffix_y, int min_overlap);
extern "C" SEXP _valr_intersect_impl(SEXP gdf_x, SEXP gdf_y, SEXP x_grp_indexes, SEXP y_grp_indexes, SEXP invert, SEXP suffix_x, SEXP suffix_y, SEXP min_overlap) {
  BEGIN_CPP11
    return cpp11::as_sexp(intersect_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_x), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x_grp_indexes), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(y_grp_indexes), cpp11::as_cpp<cpp11::decay_t<bool>>(invert), cpp11::as_cpp<cpp11::decay_t<std::string>>(suffix_x), cpp11::as_cpp<cpp11::decay_t<std::string>>(suffix_y), cpp11::as_cpp<cpp11::decay_t<int>>(min_overlap)));
  END_CPP11
}
// makewindows.cpp
cpp11::writable::data_frame makewindows_impl(cpp11::data_frame df, int win_size, int num_win, int step_size, bool reverse);
extern "C" SEXP _valr_makewindows_impl(SEXP df, SEXP win_size, SEXP num_win, SEXP step_size, SEXP reverse) {
  BEGIN_CPP11
    return cpp11::as_sexp(makewindows_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(df), cpp11::as_cpp<cpp11::decay_t<int>>(win_size), cpp11::as_cpp<cpp11::decay_t<int>>(num_win), cpp11::as_cpp<cpp11::decay_t<int>>(step_size), cpp11::as_cpp<cpp11::decay_t<bool>>(reverse)));
  END_CPP11
}
// merge.cpp
cpp11::writable::data_frame merge_impl(cpp11::data_frame gdf, int max_dist, bool collapse);
extern "C" SEXP _valr_merge_impl(SEXP gdf, SEXP max_dist, SEXP collapse) {
  BEGIN_CPP11
    return cpp11::as_sexp(merge_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf), cpp11::as_cpp<cpp11::decay_t<int>>(max_dist), cpp11::as_cpp<cpp11::decay_t<bool>>(collapse)));
  END_CPP11
}
// partition.cpp
cpp11::writable::data_frame partition_impl(cpp11::data_frame gdf, int max_dist);
extern "C" SEXP _valr_partition_impl(SEXP gdf, SEXP max_dist) {
  BEGIN_CPP11
    return cpp11::as_sexp(partition_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf), cpp11::as_cpp<cpp11::decay_t<int>>(max_dist)));
  END_CPP11
}
// random.cpp
cpp11::writable::data_frame random_impl(cpp11::data_frame genome, double length, int n, int seed);
extern "C" SEXP _valr_random_impl(SEXP genome, SEXP length, SEXP n, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(random_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(genome), cpp11::as_cpp<cpp11::decay_t<double>>(length), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// shuffle.cpp
cpp11::writable::data_frame shuffle_impl(cpp11::data_frame df, cpp11::data_frame incl, bool within, int max_tries, int seed);
extern "C" SEXP _valr_shuffle_impl(SEXP df, SEXP incl, SEXP within, SEXP max_tries, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(shuffle_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(df), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(incl), cpp11::as_cpp<cpp11::decay_t<bool>>(within), cpp11::as_cpp<cpp11::decay_t<int>>(max_tries), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// subtract.cpp
cpp11::writable::data_frame subtract_impl(cpp11::data_frame gdf_x, cpp11::data_frame gdf_y, cpp11::integers x_grp_indexes, cpp11::integers y_grp_indexes, int min_overlap);
extern "C" SEXP _valr_subtract_impl(SEXP gdf_x, SEXP gdf_y, SEXP x_grp_indexes, SEXP y_grp_indexes, SEXP min_overlap) {
  BEGIN_CPP11
    return cpp11::as_sexp(subtract_impl(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_x), cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(gdf_y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x_grp_indexes), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(y_grp_indexes), cpp11::as_cpp<cpp11::decay_t<int>>(min_overlap)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_valr_bed12toexons_impl", (DL_FUNC) &_valr_bed12toexons_impl, 1},
    {"_valr_closest_impl",      (DL_FUNC) &_valr_closest_impl,      6},
    {"_valr_complement_impl",   (DL_FUNC) &_valr_complement_impl,   2},
    {"_valr_coverage_impl",     (DL_FUNC) &_valr_coverage_impl,     5},
    {"_valr_dist_impl",         (DL_FUNC) &_valr_dist_impl,         5},
    {"_valr_flank_impl",        (DL_FUNC) &_valr_flank_impl,        8},
    {"_valr_gcoverage_impl",    (DL_FUNC) &_valr_gcoverage_impl,    2},
    {"_valr_intersect_impl",    (DL_FUNC) &_valr_intersect_impl,    8},
    {"_valr_makewindows_impl",  (DL_FUNC) &_valr_makewindows_impl,  5},
    {"_valr_merge_impl",        (DL_FUNC) &_valr_merge_impl,        3},
    {"_valr_partition_impl",    (DL_FUNC) &_valr_partition_impl,    2},
    {"_valr_random_impl",       (DL_FUNC) &_valr_random_impl,       4},
    {"_valr_shuffle_impl",      (DL_FUNC) &_valr_shuffle_impl,      5},
    {"_valr_subtract_impl",     (DL_FUNC) &_valr_subtract_impl,     5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_valr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
