# Generated by cpp11: do not edit by hand

bed12toexons_impl <- function(x) {
  .Call(`_valr_bed12toexons_impl`, x)
}

flank_impl <- function(df, genome, both, left, right, fraction, stranded, trim) {
  .Call(`_valr_flank_impl`, df, genome, both, left, right, fraction, stranded, trim)
}

makewindows_impl <- function(df, win_size, num_win, step_size, reverse) {
  .Call(`_valr_makewindows_impl`, df, win_size, num_win, step_size, reverse)
}

random_impl <- function(genome, length, n, seed) {
  .Call(`_valr_random_impl`, genome, length, n, seed)
}
