# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname bed_intersect
#' 
intersect_impl <- function(x, y, suffix_x = ".x", suffix_y = ".y") {
    .Call('valr_intersect_impl', PACKAGE = 'valr', x, y, suffix_x, suffix_y)
}

#' @rdname bed_merge
#'
merge_impl <- function(gdf, max_dist = 0L) {
    .Call('valr_merge_impl', PACKAGE = 'valr', gdf, max_dist)
}

#' @rdname bed_random
#'
random_impl <- function(genome, length, n, seed = 0L) {
    .Call('valr_random_impl', PACKAGE = 'valr', genome, length, n, seed)
}

