# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

absdist_impl <- function(x, y) {
    .Call(valr_absdist_impl, x, y)
}

closest_impl <- function(x, y, suffix_x, suffix_y) {
    .Call(valr_closest_impl, x, y, suffix_x, suffix_y)
}

complement_impl <- function(gdf, genome) {
    .Call(valr_complement_impl, gdf, genome)
}

coverage_impl <- function(x, y) {
    .Call(valr_coverage_impl, x, y)
}

intersect_impl <- function(x, y, suffix_x = ".x", suffix_y = ".y") {
    .Call(valr_intersect_impl, x, y, suffix_x, suffix_y)
}

makewindows_impl <- function(df, step_size = 0L, reverse = FALSE, col_start = "start", col_end = "end", col_win_size = ".win_size") {
    .Call(valr_makewindows_impl, df, step_size, reverse, col_start, col_end, col_win_size)
}

merge_impl <- function(gdf, max_dist = 0L, collapse = TRUE) {
    .Call(valr_merge_impl, gdf, max_dist, collapse)
}

random_impl <- function(genome, length, n, seed = 0L, col_chrom = "chrom", col_size = "size") {
    .Call(valr_random_impl, genome, length, n, seed, col_chrom, col_size)
}

reldist_impl <- function(x, y) {
    .Call(valr_reldist_impl, x, y)
}

shuffle_impl <- function(df, incl, within = FALSE, max_tries = 1000L, seed = 0L) {
    .Call(valr_shuffle_impl, df, incl, within, max_tries, seed)
}

subtract_impl <- function(gdf_x, gdf_y) {
    .Call(valr_subtract_impl, gdf_x, gdf_y)
}

