# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intersect_cpp <- function(df_a, df_b) {
    .Call('Rbedtools_intersect_cpp', PACKAGE = 'Rbedtools', df_a, df_b)
}

